version: '2'
services:
  mongodb:
    image: jmery/np-mongodb
    command: --strategy at-once
    environment:
      HAB_MONGODB: "[mongod.net]\nbind_ip = '0.0.0.0'\n[mongod.security]\ncluster_auth_mode = ''"
  national-parks:
<<<<<<< HEAD
    image: jmery/national-parks:6.7.0
=======
    image: jmery/national-parks
>>>>>>> 5137fc0eeb569fb774c21ff27b4f6e0ea4faccd2
    ports:
      - 8081:8080
      - 9631:9631
    links:
      - mongodb
    depends_on:
      - mongodb
    command: --strategy at-once --channel stable --peer mongodb --bind database:np-mongodb.default
